# Import irregularly gridded reservoir models in XARRAY

In [93]:
import numpy as np
import pandas as pd
import xarray as xr
import scipy.spatial

In [72]:
size = 100

In [73]:
#fluid = np.random.rand(4, 3)

In [74]:
#faultblock

In [75]:
#ntg = np.random.random_sample(size=size)
#ntg

In [76]:
zone = np.random.randint(0,64+1, size=size)
zone

array([18, 60, 47, 46, 51, 28, 58, 16, 31, 58,  3, 21, 18, 27, 54, 36, 61,
       25,  3,  3, 56, 59, 19, 18, 39,  8, 63, 51, 41, 23, 12, 41, 16, 35,
       57,  7, 14,  2, 33,  6, 10,  9, 16, 59, 49, 49, 31, 41, 23, 37, 37,
       16, 63, 46, 45, 33, 56, 31,  1, 27, 43, 34, 25, 23, 41, 20, 12,  8,
       27, 33,  0, 64,  2, 23,  8, 11, 32, 41, 24, 56, 16, 25, 43, 29, 28,
       55, 21,  7,  5, 36, 58, 30,  9,  5, 19, 56, 47, 52, 51, 26])

In [77]:
x = np.random.random(size=size) * 100
x

array([77.20289729, 10.77449709, 52.52410315,  3.78451602, 13.85905499,
       43.82077618, 22.70911536, 81.18461328, 14.55098906, 57.15219901,
       30.24801654, 44.85631678, 46.22662032, 78.93506421, 75.09193942,
        8.01878793, 79.89257122, 32.55740058, 10.80813451, 11.77664713,
       17.91142702, 80.70079128,  1.30477883, 49.50918168, 75.18841137,
       85.49713434,  6.30711744, 60.4043115 , 95.08831531, 34.73704773,
       40.08713176, 57.50973123, 76.80185527, 77.51885261, 92.42820648,
       34.12088698, 33.98588006, 45.91701782, 70.12630875, 78.52638549,
       21.63024256, 90.46883654, 62.00881416, 77.75479681, 88.8839235 ,
       84.51294167, 39.79642458,  9.42136734, 18.25963093, 28.46006614,
       56.991963  , 26.93685588, 77.34927871, 98.44175503, 81.51549335,
       74.04724127, 40.33265893, 57.27945659, 14.21762982, 50.77485805,
       39.55078138, 52.30282514, 73.22514828, 83.17656553, 85.05573089,
       81.71468362, 49.0530817 , 46.78565165, 66.25355804, 62.18132239,
       77.52023761, 27.65736684, 23.96072215, 32.66863624, 45.83485684,
       63.30459554, 42.92395647, 41.53648323, 85.7263044 , 30.5278432 ,
       76.77612428, 60.83400131, 56.33106287, 55.29408719, 16.71642074,
       92.22117957, 77.84261603, 76.37129616, 82.17733357, 79.17166479,
       43.61443489, 95.27181656, 18.30330527, 91.64171497, 38.76514854,
       76.11507461,  4.50875564, 31.61768766, 95.27847666, 32.27867655])

In [78]:
y = np.random.random(size=size) * 200
y

array([ 63.89578264,  18.96061811, 149.69130481,  45.43926061,
        87.2740845 ,  39.7577606 ,  51.87799546, 165.20141599,
       141.19119697, 134.19692224,  71.62067176, 199.66303426,
        21.4560625 ,   5.99930245,  59.5872386 ,   7.51424967,
        37.73805652, 125.11159413, 181.54903501, 115.22147226,
        37.04650052, 187.0870838 ,  60.66580289,  96.45140868,
        80.39144856, 107.94715229,  52.63302401,  86.35669809,
       149.86176995, 108.29328128, 108.53988404, 157.5651887 ,
       135.21078421,  18.12932616, 193.18642311,  24.17845236,
        47.05675567, 106.02713008,  64.4656168 , 138.03573868,
        22.71116354,  61.4791871 ,  45.48158608, 183.43501632,
         4.42484559,  10.92345558, 144.17002363, 101.36556943,
        79.23449323,   2.61633679, 158.91367746,  19.92534665,
       128.12525591,  80.5278113 ,  81.11539903,  67.34374606,
        80.76399187,  75.66966869, 108.27065689, 197.87841164,
        46.13599082, 163.63289055,  23.0341119 , 161.95863459,
       130.12349129, 132.00033015, 163.47980177,  99.22104166,
       106.76045416, 177.91835198, 131.09734514, 135.87199007,
       146.06058561, 106.22667855, 189.33329649,  99.58355526,
       161.03390394,  33.62549725,  30.700339  ,  14.39957242,
       129.4714186 , 121.48098716, 142.33661978, 142.06662661,
       176.38316747, 170.72546019,  88.30397203, 130.9947866 ,
       169.54574362, 113.15625092,  79.32964854,  78.17930605,
        98.35821138,  41.88722637, 102.25370592,  71.34456767,
        79.28623233, 167.32842563, 114.01103452,  54.7593859 ])

In [79]:
z = np.random.random(size=size) * 20
z

array([ 6.67551881, 12.18705894, 11.35016942, 10.71364763,  6.09242934,
       19.5041131 ,  5.42968717,  4.71635682,  8.3314069 , 19.937747  ,
       16.51153059, 15.93760438,  3.0923487 ,  4.73370401, 15.00713497,
        1.35745154,  9.0689133 , 14.94507652, 17.18141163,  4.15796003,
       15.06882918,  9.8333633 ,  0.62939494,  4.00360327, 19.33286843,
        7.49602539, 13.21606267, 13.05453731, 10.46188732,  3.09043851,
       17.86649339, 12.33653023, 19.55960157, 16.64031188,  7.93622384,
       11.02904121,  7.09872789, 18.23687755, 16.90701716, 17.74278856,
       18.73248254,  1.16664183, 17.5217567 , 16.23452158,  5.28276141,
       16.7457992 ,  4.6835667 , 13.84678374,  0.29640897, 15.3258187 ,
       15.0023833 ,  0.36424938,  7.40832697,  4.10060385, 14.3610254 ,
       19.87185562,  4.98160209, 12.5996008 ,  7.05149503, 14.50448676,
       15.68536435,  9.5174747 ,  1.42804445, 10.49715309,  6.66110336,
       16.61353871,  0.82875419, 18.80761311,  4.40380237, 16.69230689,
       16.28696376, 17.43781541,  3.67983552,  7.38382202,  9.81145089,
       16.80999478,  9.15567986,  8.88139249,  1.32997534,  0.79074227,
        4.83280722,  7.73069519,  0.62100125, 10.69880652,  9.49261446,
       12.80336084,  3.73477865, 14.92968301, 10.59996413,  8.4218029 ,
       12.4853188 , 17.23151193, 17.11643606,  4.91680099, 16.30193124,
        4.71437229, 11.33580913, 12.54980842, 19.62042185, 10.13606476])

In [57]:
a = xr.DataArray(zone, coords=[x, y, z], dims=['x', 'y', 'z'])

In [58]:
a

<xarray.DataArray (x: 3, y: 3, z: 3)>
array([[[34, 14,  2],
        [55,  3, 21],
        [58, 26, 29]],

       [[22, 46, 49],
        [21, 59, 23],
        [19, 33, 12]],

       [[36, 55, 20],
        [ 2, 50, 58],
        [ 0, 38, 64]]])
Coordinates:
  * x        (x) float64 28.47 61.32 56.89
  * y        (y) float64 28.44 150.4 31.37
  * z        (z) float64 12.38 2.166 19.77

In [100]:
dic = {'zone': zone, 'x': x, 'y': y, 'z': z}
df = pd.DataFrame.from_dict(dic)

In [101]:
df

    zone          x           y          z
0     18  77.202897   63.895783   6.675519
1     60  10.774497   18.960618  12.187059
2     47  52.524103  149.691305  11.350169
3     46   3.784516   45.439261  10.713648
4     51  13.859055   87.274085   6.092429
5     28  43.820776   39.757761  19.504113
6     58  22.709115   51.877995   5.429687
7     16  81.184613  165.201416   4.716357
8     31  14.550989  141.191197   8.331407
9     58  57.152199  134.196922  19.937747
10     3  30.248017   71.620672  16.511531
11    21  44.856317  199.663034  15.937604
12    18  46.226620   21.456062   3.092349
13    27  78.935064    5.999302   4.733704
14    54  75.091939   59.587239  15.007135
15    36   8.018788    7.514250   1.357452
16    61  79.892571   37.738057   9.068913
17    25  32.557401  125.111594  14.945077
18     3  10.808135  181.549035  17.181412
19     3  11.776647  115.221472   4.157960
20    56  17.911427   37.046501  15.068829
21    59  80.700791  187.087084   9.833363
22    19   1.304779   60.665803   0.629395
23    18  49.509182   96.451409   4.003603
24    39  75.188411   80.391449  19.332868
25     8  85.497134  107.947152   7.496025
26    63   6.307117   52.633024  13.216063
27    51  60.404312   86.356698  13.054537
28    41  95.088315  149.861770  10.461887
29    23  34.737048  108.293281   3.090439
..   ...        ...         ...        ...
70     0  77.520238  131.097345  16.286964
71    64  27.657367  135.871990  17.437815
72     2  23.960722  146.060586   3.679836
73    23  32.668636  106.226679   7.383822
74     8  45.834857  189.333296   9.811451
75    11  63.304596   99.583555  16.809995
76    32  42.923956  161.033904   9.155680
77    41  41.536483   33.625497   8.881392
78    24  85.726304   30.700339   1.329975
79    56  30.527843   14.399572   0.790742
80    16  76.776124  129.471419   4.832807
81    25  60.834001  121.480987   7.730695
82    43  56.331063  142.336620   0.621001
83    29  55.294087  142.066627  10.698807
84    28  16.716421  176.383167   9.492614
85    55  92.221180  170.725460  12.803361
86    21  77.842616   88.303972   3.734779
87     7  76.371296  130.994787  14.929683
88     5  82.177334  169.545744  10.599964
89    36  79.171665  113.156251   8.421803
90    58  43.614435   79.329649  12.485319
91    30  95.271817   78.179306  17.231512
92     9  18.303305   98.358211  17.116436
93     5  91.641715   41.887226   4.916801
94    19  38.765149  102.253706  16.301931
95    56  76.115075   71.344568   4.714372
96    47   4.508756   79.286232  11.335809
97    52  31.617688  167.328426  12.549808
98    51  95.278477  114.011035  19.620422
99    26  32.278677   54.759386  10.136065

[100 rows x 4 columns]

In [69]:
xd = df.set_index(['x','y','z']).to_xarray()

In [70]:
xd

<xarray.Dataset>
Dimensions:  (x: 12, y: 12, z: 12)
Coordinates:
  * x        (x) float64 13.56 28.75 43.97 62.74 ... 112.5 133.3 157.8 193.7
  * y        (y) float64 13.56 28.75 43.97 62.74 ... 112.5 133.3 157.8 193.7
  * z        (z) float64 2.017 2.9 3.228 7.968 9.777 ... 14.47 14.84 15.89 17.36
Data variables:
    zone     (x, y, z) float64 nan nan nan nan nan nan ... nan nan nan nan nan

In [ ]:
%matplotlib inline

import matplotlib.pyplot as plt
ax = plt.subplot(projection=ccrs.PlateCarree())
air2d = air.isel(time= 0)
air2d.plot.pcolormesh('Lon', 'Lat');

## Nearest neighbour look-up

In [108]:
rx = np.arange(0,100,10)
ry = np.arange(0,200,20)
rz = np.arange(0,20,4)

In [113]:
a,b,c = np.meshgrid(rx,ry,rz)

In [118]:
grid_dic = {'x': a.ravel(), 'y': b.ravel(), 'z': c.ravel()}
grid_df = pd.DataFrame.from_dict(grid_dic)

In [121]:
grid_df.head()

   x  y   z
0  0  0   0
1  0  0   4
2  0  0   8
3  0  0  12
4  0  0  16

In [90]:
df.values

array([[ 58.        , 133.34254204, 133.34254204,   9.77653206],
       [ 17.        ,  43.97142222,  43.97142222,   2.01669088],
       [ 47.        , 106.35900654, 106.35900654,  10.53889566],
       [ 13.        , 157.79245508, 157.79245508,   2.90026241],
       [  7.        , 101.40480212, 101.40480212,  17.35559807],
       [  3.        , 193.65077464, 193.65077464,   7.9679037 ],
       [ 45.        ,  86.96745366,  86.96745366,  13.46242288],
       [  3.        ,  62.74246137,  62.74246137,  14.47331791],
       [ 64.        ,  69.8639129 ,  69.8639129 ,   3.22839593],
       [ 34.        ,  13.56296893,  13.56296893,  14.83621566],
       [ 57.        , 112.48800468, 112.48800468,  11.78789307],
       [ 14.        ,  28.75151759,  28.75151759,  15.89047728]])

In [94]:
lookup = scipy.spatial.KDTree(df.values, leafsize=10)

In [97]:
lookup.query((0,20,20,20))

(19.132859099957674, 11)

In [99]:
scipy.spatial.distance.cdist

In [145]:
def nearest_neighbour(data, grid):
    dist = scipy.spatial.distance.cdist(grid, data[:,1:4])
    idx = np.argmin(d, axis=1)
    return idx

In [150]:
idx = nearest_neighbour(df.values, grid_df.values)

df.iloc[idx]['zone']

15    36
15    36
15    36
15    36
15    36
15    36
15    36
15    36
15    36
15    36
15    36
49    37
49    37
49    37
49    37
79    56
49    37
49    37
49    37
49    37
79    56
49    37
49    37
49    37
49    37
12    18
12    18
12    18
49    37
49    37
      ..
74     8
74     8
74     8
74     8
74     8
74     8
74     8
74     8
74     8
74     8
69    33
69    33
69    33
69    33
69    33
21    59
21    59
43    59
69    33
69    33
21    59
21    59
21    59
43    59
43    59
21    59
85    55
85    55
85    55
85    55
Name: zone, Length: 500, dtype: int64